version: '3'  # version of compose format 

services:
  app1:
    build: ./web  # path is relative to docker-compose.yml localtion
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      PYTHONUNBUFFERED: 0
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    ports:
      - 5000:80  # host:container
    volumes: ['./web:/app']
    networks:
      app_net:
        ipv4_address: 172.23.0.3
    stdin_open: true
    tty: true

  app2:
    build: ./web  # path is relative to docker-compose.yml localtion
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      PYTHONUNBUFFERED: 0
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    ports:
      - 5001:80  # host:container
    volumes: ['./web:/app']
    networks:
      app_net:
        ipv4_address: 172.23.0.4
    stdin_open: true
    tty: true

  app3:
    build: ./web  # path is relative to docker-compose.yml localtion
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      PYTHONUNBUFFERED: 0
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
    ports:
      - 5002:80  # host:container
    volumes: ['./web:/app']
    networks:
      app_net:
        ipv4_address: 172.23.0.5
    stdin_open: true
    tty: true

networks:
    app_net:
        ipam:
            driver: default
            config:
                - subnet: 172.23.0.0/16